/**
 * Compiler tests — parser + Flue emitter.
 *
 * No model, no network, no Python. These exercise the two pieces that are the
 * heart of Baton: turning PiperFlow text into a validated AST, and turning that
 * AST into a runnable workflow. Every assertion checks real behaviour, not a
 * printed log line.
 *
 * Run:  npm test            (all tests)
 *       node --import tsx --test test/compiler.test.ts
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parsePiperFlow } from '../src/compiler/parse.js';
import { emitFlueWorkflow, laneKey } from '../src/compiler/emit.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// The richest committed sample — pools, a parallel gateway, a subprocess,
// a message event, four lanes. Parsing/compiling it end-to-end is the
// integration-level proof that the contract holds.
const orderDsl = readFileSync(join(root, 'src', 'samples', 'order-fulfilment.pf'), 'utf8');

// ---------------------------------------------------------------------------
// Parser: the real sample must produce a well-formed, fully-connected AST.
// ---------------------------------------------------------------------------

test('parser: order-fulfilment yields a non-trivial, fully-connected AST', () => {
  const ast = parsePiperFlow(orderDsl);

  assert.ok(ast.elements.length > 0, 'has elements');
  assert.ok(ast.lanes.length >= 4, 'has the expected swimlanes');
  assert.ok(ast.edges.length > 0, 'has connections');

  const starts = ast.elements.filter((e) => e.category === 'event' && e.variant === 'start');
  assert.equal(starts.length, 1, 'exactly one start event');
  assert.ok(
    ast.elements.some((e) => e.category === 'event' && e.variant === 'end'),
    'has an end event',
  );
});

test('parser: every element participates in at least one connection (no orphans)', () => {
  const ast = parsePiperFlow(orderDsl);
  const connected = new Set<string>();
  for (const e of ast.edges) {
    connected.add(e.from);
    connected.add(e.to);
  }
  const orphans = ast.elements.filter((e) => !connected.has(e.id));
  assert.deepEqual(orphans, [], 'no orphan elements');
});

test('parser: recognises the full element taxonomy from the sample', () => {
  const ast = parsePiperFlow(orderDsl);
  const variants = (cat: string) =>
    ast.elements.filter((e) => e.category === cat).map((e) => e.variant);

  // The sample deliberately exercises these so the taxonomy is proven on real input.
  assert.ok(variants('gateway').includes('parallel'), 'parsed a parallel gateway');
  assert.ok(variants('activity').includes('subprocess'), 'parsed a subprocess');
  assert.ok(variants('event').includes('message'), 'parsed a message event');
});

test('parser: pools and lanes are captured with their nesting', () => {
  const ast = parsePiperFlow(orderDsl);
  // Retailer pool owns three lanes; Customer sits in the default (no) pool.
  const retailerLanes = ast.lanes.filter((l) => l.pool === 'Retailer');
  assert.ok(retailerLanes.length >= 3, 'Retailer pool has its child lanes');
  assert.ok(ast.lanes.some((l) => l.name === 'Customer'), 'Customer lane present');
});

test('parser: chained edges (a -> b -> c) expand into individual hops', () => {
  const ast = parsePiperFlow(`title: chain
lane: A
(start) as s
[Middle] as m
(end) as e
s -> m -> e`);
  // One chained line must become two edges, not one.
  assert.equal(ast.edges.length, 2);
  assert.ok(ast.edges.some((e) => e.from === 's' && e.to === 'm'));
  assert.ok(ast.edges.some((e) => e.from === 'm' && e.to === 'e'));
});

// ---------------------------------------------------------------------------
// Emitter: the AST must become an idiomatic, runnable Flue workflow.
// ---------------------------------------------------------------------------

test('emit: produces a valid Flue workflow scaffold', () => {
  const ast = parsePiperFlow(orderDsl);
  const code = emitFlueWorkflow(ast, { name: 'order-fulfilment', model: 'vllm/Capybara' });

  assert.match(code, /AUTO-GENERATED by baton/);
  assert.match(code, /createAgent/);
  assert.match(code, /defineAgentProfile/);
  assert.match(code, /subagents:\s*\[/, 'lanes wired as sub-agents on the coordinator');
  assert.match(code, /await session\.task/, 'steps delegate via session.task');
  assert.match(code, /vllm\/Capybara/, 'model specifier threaded through');
  assert.match(code, /npx flue run gen-order-fulfilment/, 'run hint names the workflow correctly');
});

test('emit (ADR-6): parallel gateways compile to SEQUENTIAL branches', () => {
  // Flue serialises a coordinator session to one operation at a time, so
  // concurrent session.task() calls throw "session is busy". Parallel branches
  // must therefore be emitted sequentially. This test pins that decision so a
  // future "just use Promise.all" regression is caught immediately.
  const ast = parsePiperFlow(orderDsl);
  assert.ok(
    ast.elements.some((e) => e.variant === 'parallel'),
    'precondition: sample has a parallel gateway',
  );
  const code = emitFlueWorkflow(ast, { name: 'order-fulfilment', model: 'vllm/Capybara' });
  assert.match(code, /run sequentially/, 'parallel branch carries the ADR-6 constraint note');
});

test('emit: each distinct lane becomes exactly one sub-agent (dedup by key)', () => {
  const ast = parsePiperFlow(orderDsl);
  const code = emitFlueWorkflow(ast, { name: 'order-fulfilment', model: 'vllm/Capybara' });
  // laneKey is what the emitter uses as the sub-agent name; count its declarations.
  const declared = ast.lanes.map((l) => laneKey(l.name));
  const unique = new Set(declared);
  for (const key of unique) {
    const decls = code.split(`name: ${JSON.stringify(key)},`).length - 1;
    assert.equal(decls, 1, `lane '${key}' declared exactly once`);
  }
});

test('emit: a minimal linear process compiles to a straight-line run() body', () => {
  const dsl = `title: linear
lane: Eng
(start) as s
[Build] as build
(end) as e
s -> build -> e`;
  const code = emitFlueWorkflow(parsePiperFlow(dsl), { name: 'linear', model: 'vllm/Capybara' });
  assert.match(code, /await session\.task\("Build"/);
  // No gateway machinery should be generated for a linear flow.
  assert.doesNotMatch(code, /_decision/, 'no decision branching for a linear process');
});
