/**
 * The PiperFlow grammar, given to the model so its output is machine-parseable.
 * Mirrors the official ProcessPiper syntax exactly, with the REAL colour themes.
 * Using the DSL itself as the structured-output contract is more robust with a
 * local model than JSON mode — and it's the same artifact we render + compile.
 */
export const DSL_SPEC = `You author PiperFlow, a text format for business process diagrams.
Output ONLY the PiperFlow document — no prose, no markdown fences, no explanation.

DIAGRAM CONFIG (optional lines, any order)
  title: <process title>
  colourtheme: <THEME>      # one of: GREENTURTLE, BLUEMOUNTAIN, GREYWOOF,
                            #   ORANGEPEEL, SUNFLOWER, PURPLERAIN, RUBYRED,
                            #   TEALWATERS, SEAFOAMS
  width: <pixels>           # optional
  footer: <footer text>     # optional

STRUCTURE
  lane: <name>              # top-level lane (no enclosing pool)
  pool: <name>              # opens a pool; lanes below belong to it
      lane: <name>

DATA OBJECTS (optional — adds the BPMN data layer; makes the output Executable)
  data: <name>              # untyped artifact
  data: <name> : <Type>     # typed artifact (becomes a BPMN itemDefinition)

ELEMENTS — each MUST end with "as <id>". Indent under its lane.
  Events (parentheses):
    (start) as <id>                                # start event
    (end) as <id>                                  # end event
    (@timer <text>) as <id>                        # timer event
    (@intermediate <text>) as <id>                 # intermediate event
    (@message <text>) as <id>                      # message event
    (@signal <text>) as <id>                       # signal event
    (@conditional <text>) as <id>                  # conditional event
    (@link <text>) as <id>                         # link event
  Activities (brackets):
    [<text>] as <id>                               # task (default)
    [@subprocess <text>] as <id>                   # subprocess
    # Optional data I/O block — names refer to declared data objects above.
    [Validate Order] as validate { in: order; out: validated_order }
  Gateways (angle brackets):
    <<text>?> as <id>                              # EXCLUSIVE (default) — one branch, Yes/No
    <@parallel <text>> as <id>                     # PARALLEL — ALL outgoing branches run
    <@inclusive <text>?> as <id>                   # INCLUSIVE — one OR MORE branches
    <@event <text>> as <id>                        # event-based gateway

CONNECTIONS — placed AFTER all elements.
  Chain with ->, optionally a trailing ": label" on the last hop.
  Use Yes/No labels on exclusive gateways so the compiler can branch.
    login->enter_keyword
    start->login->enter_keyword->end
    result_found->display_result: Yes
  Optional per-hop connection sides (visual only): start-(bottom, top)->login

GATEWAY SEMANTICS (critical — the compiler branches on Yes/No labels)
- Phrase each exclusive gateway as a QUESTION whose Yes answer is unambiguous.
- Put the SAME kind of outcome on the SAME branch across gateways.
- The Yes branch is the affirmative answer; the No branch is the negative.
- Recovery/retry steps belong on the branch that confirms the problem (e.g. the
  Yes branch of a "...Failed?" gateway), NOT on the branch where nothing is wrong.
- Both paths of a decision must eventually reach (end); avoid dead-ends.
- Correct retry pattern:  <Payment Failed?> yes->retry-><Retry Failed?> yes->cancel,
  no->fulfill ; and the outer gateway's no-> also fulfill (the success rejoin).

RULES
- Exactly one (start) and one (end).
- Element ids are lowercase snake_case and unique.
- Every id referenced in a connection must be declared above.
- EVERY element MUST appear in at least one connection — do not declare any element
  you do not wire into the flow. If a step is not part of the path, omit it.
- Indentation is not required but improves readability.

EXAMPLE
  title: Sample Test Process
  colourtheme: BLUEMOUNTAIN
      lane: End User
          (start) as start
          [Enter Keyword] as enter_keyword
          (end) as end
  pool: System Search
      lane: Database System
          [Login] as login
          [Search Records] as search_records
          <Result Found?> as result_found
          [Display Result] as display_result
          [Logout] as logout
      lane: Log System
          [Log Error] as log_error

  start->login: User Auth
  login->enter_keyword: Authenticated
  enter_keyword->search_records: Search
  search_records->result_found: Result
  result_found->display_result: Yes
  display_result->logout->end
  result_found->log_error: No
  log_error->display_result

  footer: Generated by Baton
`;
