import type { ProcessAST, ProcessElement } from './types.js';
import { isStart } from './types.js';

export interface SkillWireEntry {
  name: string;
  importPath: string;
  source: string;
  installs: number;
  compatible: boolean;
  reason?: string;
}

export interface EmitOptions {
  /** Workflow name (becomes the file stem / Flue workflow name). */
  name: string;
  /** Model specifier, e.g. `vllm/Capybara`. */
  model: string;
  /** Optional locked-ecosystem skills per lane (from `skills.wiring.json`). */
  skillWiring?: Record<string, SkillWireEntry[]>;
}

/** Lowercased slug used as the Flue sub-agent `name`. */
export const laneKey = (lane: string): string =>
  lane.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '').toLowerCase();

const roleInstructions = (lane: string, pool?: string): string =>
  `You are the "${lane}" swimlane${pool ? ` (pool: ${pool})` : ''}. Perform assigned steps accurately. If you have tools available, USE THEM to do the work concretely instead of guessing. Respond concisely with the result.`;

/**
 * Compile a ProcessAST into a runnable Flue workflow module.
 *
 * Idiomatic Flue: each swimlane is a `defineAgentProfile` sub-agent declared on
 * a coordinator agent. Steps delegate via `session.task(label, { agent })`.
 *
 *   lane            → defineAgentProfile + subagent on the coordinator
 *   task/subprocess → session.task(label, { agent })
 *   exclusive gw    → session.task(...) with yes/no result → if/else
 *   parallel gw     → fan out to all branches (emitted SEQUENTIALLY — Flue's
 *                     coordinator session is single-operation; see ADR-6)
 *   inclusive gw    → fan out to branches (emitted sequentially, superset behaviour)
 *
 * The output is a first-class Flue workflow: drop it in src/workflows/ and run
 * it with `flue run <name>`.
 */
export function emitFlueWorkflow(ast: ProcessAST, opts: EmitOptions): string {
  // Deduplicate lanes by key (Flue requires unique sub-agent names).
  const lanes = new Map<string, { name: string; pool?: string }>();
  for (const l of ast.lanes) {
    const key = laneKey(l.name);
    if (!lanes.has(key)) lanes.set(key, { name: l.name, pool: l.pool });
  }

  // Resolve ecosystem skills to import (unique, compatible only).
  // FIX: only attach skills whose lane EXISTS in this process, so a stale
  // skills.wiring.json from a different process can't dead-import a skill.
  const usedSkillVars = new Set<string>();
  const eco = new Map<string, { varId: string; importPath: string }>(); // name -> {var, path}
  const laneEco = new Map<string, string[]>(); // laneKey -> [varId...]
  if (opts.skillWiring) {
    for (const [lk, entries] of Object.entries(opts.skillWiring)) {
      if (!lanes.has(lk)) continue; // lane not in this process → skip
      for (const e of entries) {
        if (!e.compatible) continue;
        const varId = `skill_${e.name.replace(/[^a-z0-9]+/gi, '_')}`;
        if (!eco.has(e.name)) eco.set(e.name, { varId, importPath: e.importPath });
        (laneEco.get(lk) ?? laneEco.set(lk, []).get(lk)!).push(varId);
        usedSkillVars.add(varId);
      }
    }
  }

  const profileDecls = [...lanes.values()]
    .map((l) => {
      const key = laneKey(l.name);
      const ecoVars = laneEco.get(key) ?? [];
      const skillsSpread =
        `...(_cap_${key}.skills.length || ${ecoVars.length} ? { skills: [..._cap_${key}.skills, ${ecoVars.join(', ')}] } : {})`;
      return (
        `const _cap_${key} = capabilitiesFor(${JSON.stringify(key)});\n` +
        `const lane_${key} = defineAgentProfile({\n` +
        `  name: ${JSON.stringify(key)},\n` +
        `  description: ${JSON.stringify(`The "${l.name}" swimlane${l.pool ? ` of ${l.pool}` : ''}.`)},\n` +
        `  instructions: ${JSON.stringify(roleInstructions(l.name, l.pool))},\n` +
        `  ...(_cap_${key}.tools.length ? { tools: _cap_${key}.tools } : {}),\n` +
        `  ${skillsSpread},\n` +
        `});`
      );
    })
    .join('\n\n');

  const subagentsList = [...lanes.values()].map((l) => `lane_${laneKey(l.name)}`).join(', ');

  const byId = new Map(ast.elements.map((e) => [e.id, e] as const));
  const outFrom = (id: string) => ast.edges.filter((e) => e.from === id);
  const start = ast.elements.find(isStart);
  const body = start ? renderNode(start.id, byId, outFrom, new Set(), 2) : '  // no start element\n';

  return `// AUTO-GENERATED by baton. Do not edit by hand.
// Source process: ${ast.title}
// Run with:  npx flue run gen-${opts.name} --target node
// Each swimlane is a sub-agent on the coordinator; steps delegate via session.task().
import { createAgent, defineAgentProfile, type FlueContext } from '@flue/runtime';
import * as v from 'valibot';
import { capabilitiesFor } from '../capabilities/registry.js';
${[...eco.values()].filter((e) => usedSkillVars.has(e.varId)).map((e) => `import ${e.varId} from ${JSON.stringify(e.importPath)} with { type: 'skill' };`).join('\n')}

${profileDecls}

const coordinator = createAgent(() => ({
  model: ${JSON.stringify(opts.model)},
  instructions: ${JSON.stringify(
    `You orchestrate the "${ast.title}" business process by delegating each step to the right swimlane sub-agent.`,
  )},
  subagents: [${subagentsList}],
}));

export async function run({ init, log }: FlueContext<Record<string, unknown>>) {
  const harness = await init(coordinator);
  const session = await harness.session();

  // --- process steps (compiled from PiperFlow) ---
${body}
  return { ok: true, process: ${JSON.stringify(ast.title)} };
}
`;
}

function renderNode(
  id: string,
  byId: Map<string, ProcessElement>,
  outFrom: (id: string) => { to: string; label?: string }[],
  visited: Set<string>,
  indent: number,
): string {
  if (visited.has(id)) return `${pad(indent)}// (rejoin) ${id}\n`;
  visited.add(id);
  const el = byId.get(id);
  if (!el) return `${pad(indent)}// missing: ${id}\n`;

  if (el.category === 'event') {
    let s = `${pad(indent)}// event: ${el.variant}${el.variant === 'start' || el.variant === 'end' ? '' : ` — ${el.label}`}\n`;
    for (const e of outFrom(id)) s += renderNode(e.to, byId, outFrom, visited, indent);
    return s;
  }

  if (el.category === 'activity') {
    const note = el.variant === 'subprocess' ? ' // subprocess' : '';
    let s = `${pad(indent)}await session.task(${JSON.stringify(el.label)}, { agent: ${JSON.stringify(laneKey(el.lane))} });${note}\n`;
    for (const e of outFrom(id)) s += renderNode(e.to, byId, outFrom, visited, indent);
    return s;
  }

  // gateway
  const outs = outFrom(id);
  if (el.variant === 'exclusive' || el.variant === 'event') {
    const labeledYes = outs.find((e) => /^y/i.test(e.label ?? ''));
    const yes = labeledYes ?? outs[0];
    const no = outs.find((e) => e !== yes);
    const yesLbl = yes ? byId.get(yes.to)?.label ?? yes.to : '\u2014';
    const noLbl = no ? byId.get(no.to)?.label ?? no.to : '\u2014';

    // Validation: surface the two defects we hit in practice so they're visible
    // in the generated code AND in telemetry (via ctx.log at runtime).
    const warnings: string[] = [];
    if (!labeledYes) warnings.push('unlabeled gateway \u2014 yes/no branch order is ASSUMED, review it');
    const term = /cancel|abort|reject|decline|fail|refund|rollback|undo/i;
    const recover = /retry|continue|proceed|resume|reprocess|resend/i;
    if (yes && no && term.test(yesLbl) && recover.test(noLbl))
      warnings.push(`possible INVERTED gateway \u2014 yes\u2192${yesLbl} while no\u2192${noLbl} (a recovery step on the 'no' branch usually means the branches are swapped)`);

    let s = `${pad(indent)}// gateway "${el.label}": yes \u2192 ${yesLbl}, no \u2192 ${noLbl}\n`;
    if (warnings.length) {
      s += `${pad(indent)}// \u26a0 ${warnings.join('; ')}\n`;
      s += `${pad(indent)}log?.warn('gateway review', { gateway: ${JSON.stringify(el.label)}, lane: ${JSON.stringify(laneKey(el.lane))}, warnings: ${JSON.stringify(warnings)} });\n`;
    }
    s += `${pad(indent)}const { data: ${el.id}_decision } = await session.task(${JSON.stringify(el.label)}, {\n`;
    s += `${pad(indent)}  agent: ${JSON.stringify(laneKey(el.lane))},\n`;
    s += `${pad(indent)}  result: v.object({ answer: v.picklist(['yes', 'no']) }),\n`;
    s += `${pad(indent)}});\n`;
    s += `${pad(indent)}if (${el.id}_decision.answer === 'yes') {\n`;
    if (yes) s += renderNode(yes.to, byId, outFrom, new Set(visited), indent + 2);
    s += `${pad(indent)}} else {\n`;
    if (no) s += renderNode(no.to, byId, outFrom, new Set(visited), indent + 2);
    s += `${pad(indent)}}\n`;
    return s;
  }

  // parallel / inclusive → fan out to ALL branches.
  // Flue serializes a session to one operation at a time, so concurrent
  // session.task() calls on the coordinator throw "session is busy". Emit
  // the branches SEQUENTIALLY (matching the runtime constraint) but keep the
  // parallel semantics explicit in comments: the branches are independent and
  // could run concurrently with lane-scoped sessions (see ADR-6).
  const branches = outs.map((o) => o.to);
  let s = `${pad(indent)}// ${el.variant} gateway: fan out to ${branches.length} branches (run sequentially — Flue sessions are single-operation)\n`;
  for (const b of branches) {
    const branchVisited = new Set<string>();
    const inner = renderNode(b, byId, outFrom, branchVisited, indent);
    s += `${pad(indent)}// --- branch ---\n${inner}`;
    for (const x of branchVisited) visited.add(x);
  }
  return s;
}

const pad = (n: number): string => ' '.repeat(n);
